# -*- coding: utf-8 -*-
"""FND using Decision Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3wHBfTueMnTzPsoi0oy4_0GHBXqYXFn
"""

!pip install lime gensim -q

import pandas as pd
import numpy as np
import nltk
import re

from gensim.models import Word2Vec
from gensim.corpora.dictionary import Dictionary
from gensim.models.ldamodel import LdaModel

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

from lime.lime_text import LimeTextExplainer

# ==========================
# NLTK downloads
# ==========================
nltk.download('stopwords')
nltk.download('punkt')
try:
    nltk.download('punkt_tab')  # avoids punkt_tab error in some NLTK versions
except:
    pass

from nltk.corpus import stopwords as sw
stopwords = set(sw.words("english"))

# For reproducibility
import random
np.random.seed(42)
random.seed(42)

# ==========================
# 1. Load & label data
# ==========================
df_Fake = pd.read_csv("/content/drive/MyDrive/Fake News Detection/Fake.csv")
df_True = pd.read_csv("/content/drive/MyDrive/Fake News Detection/True.csv")

df_Fake["label"] = 0   # Fake
df_True["label"] = 1   # Real

df = pd.concat([df_Fake, df_True], axis=0).reset_index(drop=True)

# ==========================
# 2. Text cleaning
# ==========================
def clean_text(t):
    t = str(t).lower()
    t = re.sub(r"http\S+", "", t)           # remove URLs
    t = re.sub(r"[^a-zA-Z ]", " ", t)       # keep only letters + spaces
    words = [w for w in t.split() if w not in stopwords]
    return " ".join(words)

df["clean"] = df["text"].astype(str).apply(clean_text)

X = df["clean"].values
y = df["label"].values

# ==========================
# 3. Train/test split (before any modeling)
# ==========================
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y,
    shuffle=True,
)

print("Train size:", len(X_train_text))
print("Test size:", len(X_test_text))

# ==========================
# 4. Topic modeling (LDA) on TRAIN only
# ==========================
tokenized_train = [nltk.word_tokenize(t) for t in X_train_text]
tokenized_train = [
    [w.lower() for w in doc if w.isalpha()]
    for doc in tokenized_train
]

dictionary = Dictionary(tokenized_train)
corpus_train = [dictionary.doc2bow(toks) for toks in tokenized_train]

NUM_TOPICS = 10
lda = LdaModel(
    corpus=corpus_train,
    num_topics=NUM_TOPICS,
    id2word=dictionary,
    passes=10,
    random_state=42,
)

def get_topic_vector_from_tokens(doc_tokens):
    bow = dictionary.doc2bow(doc_tokens)
    topic_dist = lda.get_document_topics(bow, minimum_probability=0)
    idx_probs = {idx: prob for idx, prob in topic_dist}
    return np.array([idx_probs.get(i, 0.0) for i in range(NUM_TOPICS)], dtype="float32")

def get_topic_vector_from_text(text):
    toks = [w.lower() for w in nltk.word_tokenize(text) if w.isalpha()]
    return get_topic_vector_from_tokens(toks)

topic_train = np.array([get_topic_vector_from_text(t) for t in X_train_text])
topic_test  = np.array([get_topic_vector_from_text(t) for t in X_test_text])

print("Topic train shape:", topic_train.shape)
print("Topic test shape:", topic_test.shape)

# ==========================
# 5. Word2Vec embeddings (TRAIN only)
# ==========================
w2v = Word2Vec(
    sentences=tokenized_train,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    epochs=10,
)

embedding_dim = 100

def get_avg_w2v(text, model, embedding_dim=100):
    tokens = [w.lower() for w in nltk.word_tokenize(text) if w.isalpha()]
    vecs = []
    for w in tokens:
        if w in model.wv:
            vecs.append(model.wv[w])
    if len(vecs) == 0:
        return np.zeros(embedding_dim, dtype="float32")
    return np.mean(vecs, axis=0).astype("float32")

avg_w2v_train = np.array([get_avg_w2v(t, w2v, embedding_dim) for t in X_train_text])
avg_w2v_test  = np.array([get_avg_w2v(t, w2v, embedding_dim) for t in X_test_text])

print("avg_w2v_train shape:", avg_w2v_train.shape)
print("avg_w2v_test shape:", avg_w2v_test.shape)

# ==========================
# 6. Final features: [avg_w2v | topic_vector]
# ==========================
X_train_dt = np.hstack([avg_w2v_train, topic_train])
X_test_dt  = np.hstack([avg_w2v_test,  topic_test])

print("X_train_dt shape:", X_train_dt.shape)
print("X_test_dt shape:", X_test_dt.shape)

# ==========================
# 7. Decision Tree training
# ==========================
dt = DecisionTreeClassifier(
    max_depth=25,          # cap depth to reduce overfitting
    min_samples_split=4,
    min_samples_leaf=2,
    random_state=42,
    class_weight=None,     # you can try "balanced" if classes are skewed
)

dt.fit(X_train_dt, y_train)

# ==========================
# 8. Evaluation
# ==========================
y_pred = dt.predict(X_test_dt)
y_proba = dt.predict_proba(X_test_dt)[:, 1]

acc = accuracy_score(y_test, y_pred)
print("Decision Tree Test accuracy:", acc)
print("\nClassification report:\n", classification_report(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))

# ==========================
# 9. LIME & prediction helpers for Decision Tree
# ==========================
class_names = ["FAKE", "REAL"]
explainer = LimeTextExplainer(class_names=class_names)

def dt_predict_proba(text_list):
    cleaned = [clean_text(t) for t in text_list]

    avg_vecs = np.array([get_avg_w2v(t, w2v, embedding_dim) for t in cleaned])
    topic_vecs = np.array([get_topic_vector_from_text(t) for t in cleaned])

    X_feat = np.hstack([avg_vecs, topic_vecs])
    return dt.predict_proba(X_feat)  # returns [P(FAKE), P(REAL)]

def predict_news(text):
    cleaned = clean_text(text)
    avg_vec = get_avg_w2v(cleaned, w2v, embedding_dim)
    topic_vec = get_topic_vector_from_text(cleaned)
    X_feat = np.hstack([avg_vec, topic_vec]).reshape(1, -1)
    p_real = float(dt.predict_proba(X_feat)[0][1])   # class 1 = REAL
    print("P(REAL) =", p_real)
    return "REAL" if p_real >= 0.5 else "FAKE"

# Example prediction
print(predict_news("The planet Mars blew up today"))

# Example LIME explanation on one instance
idx = 10
exp = explainer.explain_instance(
    df["text"].iloc[idx],   # original text (uncleaned) for readability
    dt_predict_proba,
    num_features=10,
)
# In Colab/Jupyter:
# exp.show_in_notebook()